# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, help_text='Example: 1234 Main Street, Anywhere, KY, USA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Example: rpitino@notUofL.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Example: +1 555-555-5555', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.CharField(help_text='Example: Rick Pitino', max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='department name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(help_text="If the department is not listed here, you must add it on the <a href='/administration/department/create'>Departments page.</a>", on_delete=django.db.models.deletion.CASCADE, to='administration.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Example: rpitino@notUofL.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Example: 502-555-1234', max_length=12),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='code',
            field=models.CharField(blank=True, help_text='Example: RT-IE-DHC. Must be less than 10 characters.', max_length=10, null=True, verbose_name='test short code'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='department',
            field=models.ForeignKey(help_text="Must be assigned to a department. If the department is not listed here, you must add it on the <a href='/administration/department/create'>Departments page.</a>", on_delete=django.db.models.deletion.CASCADE, to='administration.Department'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name of test'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: 5000.00', max_digits=7, null=True),
        ),
    ]
