# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20171026_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Example: Finance', max_length=30, unique=True, verbose_name='department name'),
        ),
    ]
