# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20171026_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=30)),
                ('model_number', models.CharField(max_length=30)),
                ('part_number', models.CharField(blank=True, max_length=30, null=True)),
                ('filter_type', models.CharField(blank=True, max_length=30, null=True)),
                ('date_code', models.CharField(blank=True, max_length=30, null=True)),
                ('nominal_height', models.PositiveIntegerField(blank=True, help_text='inches', null=True)),
                ('nominal_width', models.PositiveIntegerField(blank=True, help_text='inches', null=True)),
                ('nominal_depth', models.PositiveIntegerField(blank=True, help_text='inches', null=True)),
                ('pleat_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('pocket_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=30, null=True)),
                ('adhesive_type', models.CharField(blank=True, max_length=30, null=True)),
                ('adhesive_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('disposal', models.BooleanField(default=False)),
                ('barcode_number', models.CharField(blank=True, max_length=10, null=True)),
                ('barcode_url', models.URLField(blank=True, null=True)),
                ('quote_number', models.CharField(blank=True, max_length=30, null=True)),
                ('po_number', models.CharField(blank=True, max_length=30, null=True)),
                ('air_flow_rate', models.PositiveIntegerField()),
                ('test_dust', models.CharField(blank=True, choices=[('IF', 'ISO Fine'), ('IC', 'ISO Coarse'), ('A', 'ASHRAE')], max_length=2, null=True)),
                ('final_resistance', models.PositiveIntegerField(blank=True, help_text='in W.G.', null=True)),
                ('dust_feed_rate', models.PositiveIntegerField(blank=True, help_text='(gms / MCF)', null=True)),
                ('initial_loading_pressure', models.PositiveIntegerField(help_text='in W.G.', null=True)),
                ('hi_pulse_pressure', models.PositiveIntegerField(blank=True, help_text='in W.G.', null=True)),
                ('lo_pulse_pressure', models.PositiveIntegerField(blank=True, help_text='in W.G.', null=True)),
                ('pulse_ms_on', models.PositiveIntegerField(blank=True, help_text='in milliseconds', null=True)),
                ('pulse_ms_off', models.PositiveIntegerField(blank=True, help_text='in milliseconds', null=True)),
                ('pulse_pressure', models.PositiveIntegerField(blank=True, help_text='in W.G.', null=True)),
                ('not_to_exceed_pressure', models.PositiveIntegerField(blank=True, help_text='in W.G.', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Customer')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.TestType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
