# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='initial_loading_pressure',
            field=models.PositiveIntegerField(blank=True, help_text='in W.G.', null=True),
        ),
    ]
