# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20171031_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='location',
            field=models.CharField(choices=[('NR', 'Not Received'), ('S', 'Shipping'), ('HL', 'HVAC Lab'), ('IL', 'Industrial Lab'), ('SPL', 'Special Projects Lab')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(help_text="If the department is not listed here, you must add it on the <a href='/administration/department/create'>Departments </a>page.", on_delete=django.db.models.deletion.CASCADE, to='administration.Department'),
        ),
        migrations.AlterField(
            model_name='test',
            name='customer',
            field=models.ForeignKey(help_text="If the customer is not listed here, you must add it on the <a href='/administration/customer/create'>Customer </a>page.", on_delete=django.db.models.deletion.CASCADE, to='administration.Customer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='disposal',
            field=models.BooleanField(default=False, verbose_name='Should we dispose of filter after testing?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='dust_feed_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be grams per 1000 cubic feet of natural gas (gms / MCF).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='final_resistance',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be wg (inch water gauge).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='hi_pulse_pressure',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be wg (inch water gauge).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='initial_loading_pressure',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be wg (inch water gauge).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='lo_pulse_pressure',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be wg (inch water gauge).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='manufacturer',
            field=models.CharField(max_length=30, verbose_name='filter manufacturer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='nominal_depth',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be in inches.', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='nominal_height',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be in inches.', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='nominal_width',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement shoud be in inches.', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='not_to_exceed_pressure',
            field=models.PositiveIntegerField(blank=True, help_text='Units of measurement should be wg (inch water gauge).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pleat_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Specify the number of pleats.', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pocket_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Specify the number of pockets.', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pulse_ms_off',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be ms (milliseconds).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pulse_ms_on',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be ms (milliseconds).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pulse_pressure',
            field=models.PositiveIntegerField(blank=True, help_text='Unit of measurement should be wg (inch water gauge).', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(help_text="If the test is not listed here, you must add it on the <a href='/administration/test-type/create'>Test Type </a>page.", on_delete=django.db.models.deletion.CASCADE, to='administration.TestType'),
        ),
    ]
