# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20171102_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='barcode #'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='department',
            field=models.ForeignKey(help_text="Must be assigned to a department. If the department is not listed here, you must add it on the <a href='/administration/department/create'>Departments</a> page.", on_delete=django.db.models.deletion.CASCADE, to='administration.Department'),
        ),
    ]
