# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='barcode_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
