# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0002_auto_20171024_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='barcode_number',
            field=models.CharField(blank=True, default=245507303, max_length=10, null=True),
        ),
    ]
