# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0003_auto_20171024_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='barcode_image',
        ),
        migrations.AlterField(
            model_name='test',
            name='barcode_number',
            field=models.CharField(blank=True, default=526997219, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='barcode_url',
            field=models.URLField(blank=True, default='C:\\Users\\Kenneth\\Desktop\\Projects\\simple-project\\staticfilesbarcodes/<django.db.models.fields.CharField>', null=True),
        ),
    ]
