# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0005_auto_20171024_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='barcode_url',
        ),
        migrations.AddField(
            model_name='test',
            name='barcode_image',
            field=models.ImageField(blank=True, default='C:\\Users\\Kenneth\\Desktop\\Projects\\simple-project\\staticfiles/barcodes/<django.db.models.fields.CharField>', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='barcode_number',
            field=models.CharField(blank=True, default=265576505, max_length=10, null=True),
        ),
    ]
