# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import testrequests.qr_code


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0007_auto_20171024_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='barcode_number',
            field=models.CharField(blank=True, default=testrequests.qr_code.get_barcode, max_length=10, null=True),
        ),
    ]
