# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0009_auto_20171024_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='barcode_image',
        ),
        migrations.RemoveField(
            model_name='test',
            name='barcode_number',
        ),
    ]
