# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0010_auto_20171024_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='type',
            new_name='test_type',
        ),
        migrations.AddField(
            model_name='test',
            name='filter_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
