# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0012_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='testtype',
            name='department',
        ),
        migrations.AlterField(
            model_name='test',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Customer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.TestType'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='TestType',
        ),
    ]
