# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrequests', '0013_auto_20171026_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='barcode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='initial_loading_pressure',
            field=models.PositiveIntegerField(help_text='in W.G.', null=True),
        ),
    ]
