# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['job_number']},
        ),
    ]
